name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create version
        id: version
        run: echo "VERSION=$(date '+%Y.%m.%d.%H%M%S')" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/adam-date-app:latest -t ${{ secrets.DOCKER_USERNAME }}/adam-date-app:${{ env.VERSION }} -f Dockerfile .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/adam-date-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/adam-date-app:${{ env.VERSION }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy ARM Template
        uses: azure/arm-deploy@v1
        with:
          scope: "resourcegroup"
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./azure-deploy.json
          parameters: >
            location=${{ secrets.AZURE_LOCATION }} 
            dockerImage=${{ secrets.DOCKER_USERNAME }}/adam-date-app:${{ env.VERSION }} 
            pgAdminPassword=${{ secrets.PG_ADMIN_PASSWORD }}

      - name: Logout from Azure
        run: az logout
